services:
  ladesa-ro-sso-development:
    hostname: devcontainer
    container_name: ladesa-ro-sso-development
    working_dir: /workspace
    build:
      context: ./
      target: sso-development
    command: tail -f /dev/null
    volumes:
      - ./:/workspace

  ladesa-ro-sso:
    container_name: ladesa-ro-sso
    build:
      context: ./
      target: sso-builder
      args:
        - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.scripts=enabled
    entrypoint: /opt/keycloak/bin/kc.sh
    command: start-dev --import-realm
    env_file:
      - .kc.env
    volumes:
      - ./services/sso/import:/opt/keycloak/data/import/
    depends_on:
      - ladesa-ro-sso-db
    networks:
      ladesa-net:
    ports:
      - 23032:8080
    labels:
      # ===================================================================
      - "traefik.enable=true"
      # ===================================================================
      - "traefik.http.services.sso.loadbalancer.server.port=8080"
      # ------------
      - "traefik.http.routers.sso.rule=Host(`sso.ladesa.localhost`)"
      - "traefik.http.routers.sso.entrypoints=websecure"
      - "traefik.http.routers.sso.tls=true"
      - "traefik.http.routers.sso.service=sso"
      # ------------
      - "traefik.http.routers.sso-insecure.rule=Host(`sso.ladesa.localhost`)"
      - "traefik.http.routers.sso-insecure.entrypoints=web"
      - "traefik.http.routers.sso-insecure.tls=false"
      - "traefik.http.routers.sso-insecure.service=sso"
      # ===================================================================

  ladesa-ro-sso-db:
    image: bitnami/postgresql:15
    container_name: ladesa-ro-sso-db

    volumes:
      - "ladesa-ro-sso-db-data:/bitnami/postgresql"
      - "./.devcontainer/volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

    env_file:
      - .kc-db.env

    networks:
      ladesa-net:

    # ports:
    #   - 23080:5432

networks:
  ladesa-net:
    external: true

volumes:
  ladesa-ro-sso-db-data:
