applicationName: ladesa-ro-sso

deployment:
  enabled: false

  replicas: 1

  containerSecurityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false

  ports:
    - containerPort: 8080
      name: web

  livenessProbe:
    path: /health/live
    port: 9000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 20
  readinessProbe:
    path: /health/ready
    port: 9000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 20
  startupProbe:
    path: /health/started
    port: 9000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 20

service:
  enabled: true
  type: NodePort
  ports:
    - name: ladesa-ro-sso
      port: 80
      targetPort: web

ingress:
  enabled: false
