name: "Continuous Deployment – K8S Kustomize"
description: "Deploy resources to kubernetes cluster using kustomize definitions"

inputs:
  pwd:
    description: "working directory"
    required: true
  deployment:
    description: "k8s deployment"
    required: true
  namespace:
    description: "k8s namespace"
    required: true

runs:
  using: composite
  steps:
    - name: deploy resources to kubernetes cluster
      shell: bash
      working-directory: ${{ inputs.pwd }}
      env:
        ENV_CONTEXT_JSON: ${{ toJson(secrets) }}
      run: |
        ENV_CONTEXT_KEY_VALUE=$( \
          echo "${ENV_CONTEXT_JSON}" \
          | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' \
        );

        echo "$ENV_CONTEXT_KEY_VALUE";

        # --from-env-file=<(env -i sh -c "set -a; ${ENV_CONTEXT_KEY_VALUE}; printenv | grep -v 

        kubectl create secret generic ladesa-ro-secrets \
          --from-env-file=<(echo "$ENV_CONTEXT_KEY_VALUE") \
          --namespace=${{ inputs.namespace }}
        ;

        # kubectl kustomize . | envsubst | kubectl apply -f -;

        # kubectl rollout restart \
        #   deployment.apps/${{ inputs.deployment }} \
        #   --namespace ${{ inputs.namespace }} \
        # ;
