name: "Continuous Deployment – K8S Kustomize"
description: "Deploy resources to kubernetes cluster using kustomize definitions"

inputs:
  env-json:
    description: "json with key value envs for the service secret"
    required: true
  pwd:
    description: "working directory"
    required: true
  deployment:
    description: "k8s deployment"
    required: true
  namespace:
    description: "k8s namespace"
    required: true

runs:
  using: composite
  steps:
    - name: deploy resources to kubernetes cluster
      shell: bash
      working-directory: ${{ inputs.pwd }}
      env:
        ENV_RUNTIME_JSON: ${{ inputs.env-json }}
      run: |
        ENV_RUNTIME_SECRET_NAME="ladesa-ro-sso-secrets";

        ENV_RUNTIME_KEY_VALUE=$( \
          echo "${ENV_RUNTIME_JSON}" \
          | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' \
        );

        kubectl create secret generic ${ENV_RUNTIME_SECRET_NAME} \
          --from-env-file=<(echo "$ENV_RUNTIME_KEY_VALUE") \
          --namespace=${{ inputs.namespace }} \
        ;

        # kubectl kustomize . | envsubst | kubectl apply -f -;

        # kubectl rollout restart \
        #   deployment.apps/${{ inputs.deployment }} \
        #   --namespace ${{ inputs.namespace }} \
        # ;
