name: "Continuous Deployment – K8S Kustomize"
description: "Deploy resources to kubernetes cluster using kustomize definitions"

inputs:
  runtime-env:
    description: "string with key value envs for the service secret"
    required: true
  pwd:
    description: "working directory"
    required: true
  deployment:
    description: "k8s deployment"
    required: true
  namespace:
    description: "k8s namespace"
    required: true

runs:
  using: composite
  steps:
    - name: deploy resources to kubernetes cluster
      shell: bash
      working-directory: ${{ inputs.pwd }}
      env:
        ENV_RUNTIME_KEY_VALUE: ${{ inputs.runtime-env }}
        ENV_RUNTIME_SECRET_NAME: "ladesa-ro-sso-secrets"
        
        K8S_DEPLOYMENT: ${{ inputs.deployment }}
        K8S_NAMESPACE: ${{ inputs.namespace }}
      run: |
        kubectl create secret generic ${ENV_RUNTIME_SECRET_NAME} \
          --namespace="${K8S_NAMESPACE}" \
          --dry-run="client" \
          -o="yaml" \
          --from-env-file=<(echo "${ENV_RUNTIME_KEY_VALUE}") \
        | kubectl apply -f -;

        # kubectl kustomize . | envsubst | kubectl apply -f -;

        # kubectl rollout restart \
        #   deployment.apps/${K8S_DEPLOYMENT} \
        #   --namespace ${K8S_NAMESPACE} \
        # ;
