name: "Continuous Deployment – K8S Kustomize"
description: "Deploy resources to kubernetes cluster using kustomize definitions"

inputs:
  pwd:
    description: "working directory"
    required: true
  deployment:
    description: "k8s deployment"
    required: true
  namespace:
    description: "k8s namespace"
    required: true

runs:
  using: composite
  steps:
    - name: deploy resources to kubernetes cluster
      shell: bash
      working-directory: ${{ inputs.pwd }}
      run: |
        kubectl kustomize . | envsubst | kubectl apply -f -;

        kubectl rollout restart \
          deployment.apps/${{ inputs.deployment }} \
          --namespace ${{ inputs.namespace }} \
        ;
