name: "Continuous Deployment – K8S"
description: "Deploy resources to kubernetes cluster"

inputs:
  runtime-env:
    description: "string with key value envs for the service secret"
    required: true
  pwd:
    description: "working directory"
    required: true
  deployment:
    description: "k8s deployment"
    required: true
  namespace:
    description: "k8s namespace"
    required: true
  config-application-name:
    description: "helm application namespace"
    default: "ladesa-ro-sso"

runs:
  using: composite
  steps:
    - name: deploy resources to kubernetes cluster
      shell: bash
      working-directory: ${{ inputs.pwd }}
      env:
        ENV_RUNTIME_KEY_VALUE: ${{ inputs.runtime-env }}
        ENV_RUNTIME_SECRET_NAME: "ladesa-ro-sso-secrets"

        K8S_DEPLOYMENT: ${{ inputs.deployment }}
        K8S_NAMESPACE: ${{ inputs.namespace }}

        HELM_APPLICATION_NAME: ${{ inputs.config-application-name }}
      run: |
        kubectl create secret generic ${ENV_RUNTIME_SECRET_NAME} \
          --namespace="${K8S_NAMESPACE}" \
          --dry-run="client" \
          -o="yaml" \
          --from-env-file=<(echo "${ENV_RUNTIME_KEY_VALUE}") \
        | kubectl apply -f -;

        helm repo add stakater https://stakater.github.io/stakater-charts
        helm repo update

        helm install ladesa-ro-sso stakater/application --dry-run --debug --namespace ${K8S_NAMESPACE} --values values.common.yml --values values.prod.yml;

        # kubectl kustomize . | envsubst | kubectl apply -f -;

        # kubectl rollout restart \
        #   deployment.apps/${K8S_DEPLOYMENT} \
        #   --namespace ${K8S_NAMESPACE} \
        # ;
