name: "Continuous Deployment – K8S"
description: "Deploy resources to kubernetes cluster"

inputs:
  helm-values:
    description: "yaml helm release values"
    required: true
  deployment:
    description: "k8s deployment"
    required: true
  namespace:
    description: "k8s namespace"
    required: true
  helm-release-name:
    description: "helm application namespace"
    default: "ladesa-ro-sso"

runs:
  using: composite
  steps:
    - name: deploy resources to kubernetes cluster
      shell: bash
      env:
        K8S_NAMESPACE: ${{ inputs.namespace }}
        K8S_DEPLOYMENT: ${{ inputs.deployment }}
        HELM_RELEASE_NAME: ${{ inputs.helm-release-name }}
        HELM_RELEASE_VALUES: ${{ inputs.helm-values }}
      run: |

        GENERIC_CHART_REPO=stakater
        GENERIC_CHART_REPO_SOURCE=https://stakater.github.io/stakater-charts
        GENERIC_CHART_NAME=stakater/application

        if [[ "$(helm search repo \"${GENERIC_CHART_NAME}\" 2>/dev/null)" == 'No results found' ]] then
          helm repo add ${GENERIC_CHART_REPO} ${GENERIC_CHART_REPO_SOURCE}
          helm repo update
        fi

        echo "${HELM_RELEASE_VALUES}" | helm upgrade -i ${HELM_RELEASE_NAME} ${GENERIC_CHART_NAME} \
          --namespace=${K8S_NAMESPACE} \
          --values=./.devops/values.common.yml \
          -f - \
        ;

        kubectl rollout restart \
          deployment.apps/${K8S_DEPLOYMENT} \
          --namespace ${K8S_NAMESPACE} \
        ;
