apiVersion: v1
kind: PersistentVolume
metadata:
  name: ladesa-ro-sso-db-development-pv
  labels:
    app: ladesa-ro-sso
spec:
  volumeMode: Filesystem
  hostPath:
    path: /mnt/storage/service/sso/development/db/data
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: x-ladesa-infra-host
              operator: In
              values:
                - "yes"
