apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesa-ro-sso
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ladesa-ro-sso
          image: "registry.ladesa.com.br/autenticacao:development"
