apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: ladesa-ro-production

patches:
  - path: deployment.yaml

# configMapGenerator:
#   - name: ladesa-ro-sso-configmap
#     env: config.properties
