name: "Continuous Deployment – Build and Push"
description: "Builds the container image and pushes into the registry"

inputs:
  setup-qemu:
    description: "Should use QEMU for container image build."
    required: false
    default: "false"

  build-image:
    description: "Should build the container image"
    required: false
    default: "true"

  push-image:
    description: "Enable built image push into the registry"
    required: false
    default: "true"

  image-name:
    description: "Valid container image name"
    required: true

  image-tag:
    description: "Valid container image tag"
    required: true

  push-image-registry-url:
    description: "Registry URL"
    required: false

  push-image-registry-username:
    description: "Registry username"
    required: false

  push-image-registry-token:
    description: "Registry password/token"
    required: false

runs:
  using: composite
  steps:
    - name: Set up QEMU
      if: ${{ inputs.setup-qemu == "true" }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login into Registry
      if: ${{ inputs.push-image == "true" }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.push-image-registry-url }}
        username: ${{ inputs.push-image-registry-username }}
        password: ${{ inputs.push-image-registry-token }}

    - name: Build and push container image to the registry
      if: ${{ inputs.build-image == "true" }}
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push-image == "true" }}
        tags: ${{ inputs.push-image-registry-url }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: sso-runtime
