apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesa-ro-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ladesa-ro-sso
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ladesa-ro-sso
    spec:
      containers:
        - name: ladesa-ro-sso
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          envFrom:
            - secretRef:
                name: ladesa-ro-sso-config
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 20
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 20
