services:
  ladesa-ro-auth-db:
    image: bitnami/postgresql:15
    container_name: ladesa-ro-auth-db

    volumes:
      - "ladesa-ro-auth-db-data:/bitnami/postgresql"
      - "./volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

    env_file:
      - .kc-db.env

    networks:
      ladesa-net:

    ports:
      - 23080:5432

  ladesa-ro-auth-theme:
    container_name: ladesa-ro-auth-theme

    build:
      context: ./images/development

    command: tail -f /dev/null

    volumes:
      - ../:/var/lib/ladesa-ro/ctx

  ladesa-ro-auth:
    container_name: ladesa-ro-auth

    build:
      context: ../
      args:
        - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.scripts=enabled

    entrypoint: /opt/keycloak/bin/kc.sh
    command: start-dev --import-realm

    env_file:
      - .kc.env

    volumes:
      - ./data/import:/opt/keycloak/data/import/

    depends_on:
      - ladesa-ro-auth-db

    networks:
      ladesa-net:

    ports:
      - 23032:5432

    labels:
      # ===================================================================
      - "traefik.enable=true"
      # ===================================================================
      - "traefik.http.services.sso.loadbalancer.server.port=8080"
      # ------------
      - "traefik.http.routers.sso.rule=Host(`sso.ladesa.localhost`)"
      - "traefik.http.routers.sso.entrypoints=websecure"
      - "traefik.http.routers.sso.tls=true"
      - "traefik.http.routers.sso.service=sso"
      # ------------
      - "traefik.http.routers.sso-insecure.rule=Host(`sso.ladesa.localhost`)"
      - "traefik.http.routers.sso-insecure.entrypoints=web"
      - "traefik.http.routers.sso-insecure.tls=false"
      - "traefik.http.routers.sso-insecure.service=sso"
      # ===================================================================

networks:
  ladesa-net:
    external: true

volumes:
  ladesa-ro-auth-db-data:
