name: "Continuous Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cd_build_push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'development' || 'production' }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-and-push
        if: false
        with:
          setup-qemu: "false"
          build-image: "true"
          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}
          push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}
          image-tag: ${{ vars.IMAGE_TAG }}
          image-name: ${{ vars.IMAGE_NAME_SSO_SERVICE  }}

  cd_deploy:
    name: Deploy to Cluster

    runs-on: deploy
    needs: [cd_build_push]

    environment:
      name: ${{ github.ref_name == 'main' && 'development' || 'production' }}
      url: ${{ vars.DEPLOY_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-k8s
        with:
          helm-values: ${{ vars.DEPLOY_HELM_VALUES }}
          deployment: ${{ vars.K8S_DEPLOYMENT }}
          namespace: ${{ vars.K8S_NAMESPACE }}
