name: "Continuous Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cd_build_push:
    name: "Build and Push (Development)"
    runs-on: ubuntu-latest
    
    environment:
      name: development

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-and-push
        with:
          setup-qemu: "false"
          build-image: "true"
          push-image: "true"
          image-name: ${{ vars.IMAGE_NAME_SSO_SERVICE  }}
          image-tag: ${{ vars.IMAGE_TAG }}
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}
          push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}

  cd_deploy_development:
    name: Deploy to Cluster (Development)

    runs-on: deploy
    needs: [cd_build_push]

    environment:
      name: development
      url: ${{ env.DEPLOYMENT_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-k8s-kustomize/action.yml
        with:
          pwd: ${{ env.DEPLOYMENT_PWD }}
          deployment: ${{ env.DEPLOYMENT_K8S_DEPLOYMENT }}
          namespace: ${{ env.DEPLOYMENT_K8S_NAMESPACE }}
