name: "Continuous Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cd_build_push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'development' || 'production' }}

    steps:
      - uses: ladesa-ro/esteira-ci-cd/actions/prepare-images-builder@main
        with:
          setup-qemu: "false"
          push-image: "true"
          # push-image-registry-url: ${{ secrets.REGISTRY_URL }}
          # push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          # push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}
          push-image-registry-url: ghcr.io
          push-image-registry-username: ${{ github.actor }}
          push-image-registry-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ladesa-ro/esteira-ci-cd/actions/image-build-push@main
        with:
          image-tag: ${{ vars.BUILD_IMAGE_TAG }}
          image-name: ${{ vars.BUILD_IMAGE_NAME_SSO_SERVICE  }}

          build-image: "true"
          build-target-tag: "sso-runtime"

          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}

  cd_deploy:
    name: Deploy to Cluster

    runs-on: deploy
    needs: [cd_build_push]

    environment:
      name: ${{ github.ref_name == 'main' && 'development' || 'production' }}
      url: ${{ vars.DEPLOY_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: ladesa-ro/esteira-ci-cd/actions/deploy-k8s-stakater-application@main
        with:
          helm-values: ${{ vars.DEPLOY_HELM_VALUES }}
          deployment: ${{ vars.K8S_DEPLOYMENT }}
          namespace: ${{ vars.K8S_NAMESPACE }}
          helm-release-name: ${{ vars.K8S_DEPLOYMENT }}
