name: "Continuous Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cd-build-push:
    name: "CD: Build and Push"
    uses: ./.github/workflows/cd-build-and-push.yml
    with:
      setup-qemu: false
      image-name: ${{ vars.IMAGE_NAME  }}
      image-tag: ${{ vars.IMAGE_TAG }}
    secrets:
      push-image-registry-url: ${{ secrets.REGISTRY_URL }}
      push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
      push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}

  cd-deploy:
    name: "CD: Deploy"
    uses: ./.github/workflows/cd-deploy.yml
    secrets: inherit
    needs: [cd-build-push]
