name: "Continuous Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cd_build_push:
    name: "Build and Push (Development)"
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - uses: actions/checkout@v4

      # - uses: ./.github/actions/build-and-push
      #   with:
      #     setup-qemu: "false"
      #     build-image: "true"
      #     push-image: "true"
      #     image-name: ${{ vars.IMAGE_NAME_SSO_SERVICE  }}
      #     image-tag: ${{ vars.IMAGE_TAG }}
      #     push-image-registry-url: ${{ secrets.REGISTRY_URL }}
      #     push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}

  cd_deploy_development:
    name: Deploy to Cluster (Development)

    runs-on: deploy
    needs: [cd_build_push]

    environment:
      name: development
      url: ${{ env.DEPLOYMENT_URL }}

    env:
      ENV_SECRETS_JSON: "${{ toJson(secrets) }}"
      ENV_VARS_JSON: "${{ toJson(vars) }}"

    steps:
      - uses: actions/checkout@v4

      - name: produce key=value with runtime env vars
        shell: bash
        run: |
          ENV_STRIP_PREFIX="RUNTIME_";

          RUNTIME_ENV_KEY_VALUE=$(\
          # para combinar objetos \
            echo '${{ env.ENV_SECRETS_JSON }} ${{ env.ENV_VARS_JSON }}' \
              | jq -s add \
          # para filtrar os valores \
              | jq --arg prefix "$ENV_STRIP_PREFIX" 'with_entries(select(.key | startswith($prefix)) | .key |= sub("^" + $prefix; ""))' \
          # para produzir linhas chave=valor \
              | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' \
          );

          echo "$RUNTIME_ENV_KEY_VALUE"

      # - uses: ./.github/actions/deploy-k8s-kustomize
      #   with:
      #     env-json: ${{ toJson(secrets) }}
      #     pwd: ${{ env.DEPLOYMENT_PWD }}
      #     deployment: ${{ env.DEPLOYMENT_K8S_DEPLOYMENT }}
      #     namespace: ${{ env.DEPLOYMENT_K8S_NAMESPACE }}
